### ISSUE TITLE
add_relation 中title 没有定义，或者说键不对

### ISSUE THREAD

**Issue by qriosa** [xiaolalala/Distant-Supervised-Chinese-Relation-Extraction#11]
按照作者提供的readme教程，一步一步走到了执行 add_relation程序时的标注部分时，出现了和评论区一样的报错。提示tail没有定义。我将`can`答应打印出来，发现是一句话。也就是说data列表的元素就是一句话，这样就没看懂作者后面使用`can[1]`作为一个键来索引entities字典是什么意思了。或许说我的data文件本来就错了？还希望作者能提供一下，can所代表的意思。或者data数据是否是一句话一句话作为元素构成的列表呢？
此外，
![image](https://user-images.githubusercontent.com/51109776/79738832-e496a180-832f-11ea-9f6c-640060d8282b.png)
这个地方作者写了一个注释，我尝试猜测了一下，可是没有才出作者的意图。因为后面
![image](https://user-images.githubusercontent.com/51109776/79738914-02640680-8330-11ea-99c1-e6623c582721.png)
  这个地方引用了tail，说明tail和entities字典中的某些值是一样的。这就有点懵了。希望作者能提示一下，谢谢。
@xiaolalala

**Comment by xiaofei05** [comment]
Fix bugs in 
* EntityMatcher.py
* SentenceSegment.py
* add_relation.ipynb

**Comment by xiaofei05** [comment]
fixed #4 #9 #7
