### ISSUE TITLE
运行add_relation文件时报如下错误，请问是什么原因？

### ISSUE THREAD

**Issue by lbys** [xiaolalala/Distant-Supervised-Chinese-Relation-Extraction#4]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-10-b0ebe21aa78f> in <module>
      3 for can in data:
      4     # can  [sentence, head, tail, segment]
----> 5     if tail not in entities[can[1]].values():
      6         can.append('NA')
      7         processed_data.append(can)

NameError: name 'tail' is not defined

**Comment by lbys** [comment]
就是在运行：
# 标注
processed_data = []
for can in data:
    # can  [sentence, head, tail, segment]
    if tail not in entities[can[1]].values():
        can.append('NA')
        processed_data.append(can)
        continue
    rel = ''
    for key, value in entities[can[1]]:
        if value==tail:
            rel = key
    
    for key, value in config.items():
        if rel in value:
            tp = key.split('_')[0].split('2')
            if check(entities[can[1]]['BaiduTAG'], tgs[tp[0]]):
                if tp[1]=='oth':
                    can.append(name[key])
                    processed_data.append(can)
                elif check(entities[can[2]]['BaiduTAG'], tgs[tp[1]]):
                    can.append(name[key])
                    processed_data.append(can)
            break
len(processed_data)时报的错误，求解答，谢谢

**Comment by JazzTheSaver** [comment]
have same problem

**Comment by tanzf** [comment]
请问怎么改？
