### ISSUE TITLE
构建数据集时关系的方向问题

### ISSUE THREAD

**Issue by failable** [xiaolalala/Distant-Supervised-Chinese-Relation-Extraction#5]
> 对筛选后的实体集合两两组合, 数据处理为[[sentence, entity_head, entity_tail, [sentence_seg]]]的格式。

这个两两组合貌似是对应SentenceSegment.py下这一部分的代码

            if len(new_eset)>1:
                for i in new_eset:
                    for j in new_eset:
                        if j!=i:
                            new_data.append([d[0], i, j, sen_seg])

请问这个(i, j)还是(j, i)，为什么不需要考虑关系方向的问题？

**Comment by xiaofei05** [comment]
这里用远监督构建数据集，如果训练语料中的句子所包含的实体对在数据库中有关系的体现，那么认为语料库中所有包含相同实体对的句子都表达此关系。所以这里只考虑实体的共线关系，而且实体在句子中出现的先后也并不代表关系的方向。
