### ISSUE TITLE
运行test_demo,pred_result的entpair 怎么转成中文

### ISSUE THREAD

**Issue by dh12306** [xiaolalala/Distant-Supervised-Chinese-Relation-Extraction#6]
如题，运行test_demo, 获得pred_result的entpair 时：
![image](https://user-images.githubusercontent.com/20471681/66384910-2b572680-e9f2-11e9-8987-bbf5097fde36.png)
结果如下：
---------------
b'10001#27142'
10001#27142
---------------
b'10001#27142'
10001#27142
---------------
b'10001#27142'
10001#27142
想问下，这些1001 跟27142是什么东东，怎么转成汉字呢，这些看着像词的id吗？是不是10001对应一个实体，27142对应一个实体？id对应的词从哪里找呢
@xiaolalala  谢谢

**Comment by dh12306** [comment]
有个word_vec_word2id.json 文件，是不是这里面找的10001 对应的实体，我看10001 对应的是“温”这个字 @xiaolalala

**Comment by xiaofei05** [comment]
{
        'sentence': 'Bill Gates is the founder of Microsoft .',
        'head': {'word': 'Bill Gates', 'id': 'xxxx', ...(other information)},
        'tail': {'word': 'Microsoft', 'id': 'xxxx', ...(other information)},
        'relation': 'xxx'
    }
entpair 对应的是数据集中的head id 和 tail id， #是分隔符。

**Comment by dh12306** [comment]
不好意思，还得请教下，由id，怎么找到对应的中文实体呢，有个train_entpair2scope.json文件，
内容如下：
'63719#73563': [377318, 377320], '63719#76364': [377320, 377325]
1、是不是有个ent2id的字典，然而这里面没有（我下了四个文件）
2、'63719#73563': [377318, 377320] 这里的 [377318, 377320],是指什么意思呢
麻烦了~~ @xiaolalala

**Comment by xiaofei05** [comment]
1. 没有ent2id的字典，可以自行去训练数据集中对应
2. 这里是关系抽取的包模式，一个实体对和所有包含该实体对的句子（即包）作为一个输入，预测这个实体对在这个包上表示出的关系。这里的  [377318, 377320]代表实体对 63719#73563包中的句子在所有句子中的索引，即所有句子中的第377318至377320个句子（包括377318 不包括377320）。

**Comment by dh12306** [comment]
明白了，非常感谢！撒花

**Comment by dh12306** [comment]
总结下就是，输入一个实体对跟包含该实体对的句子（即包，不管几句），输出一个23分类的每个类的得分，而不是考虑每个实体对在当前句子的关系分类(即单标签，多分类)

**Comment by dh12306** [comment]
@xiaolalala 您好，再请教个问题，项目里的远程监督体现在哪呢，
1、是selector哪里吗，比如使用attention获取某实体对 最符合的那种关系的句子？（这句话来自[https://blog.csdn.net/m0_37565948/article/details/84999919](url)，截图如下
----------------------------------
![image](https://user-images.githubusercontent.com/20471681/66468625-10031e80-eab9-11e9-86b6-9c1cef4f47ae.png)
----------------------------------
但是项目的输出（test_demo.py里的pred_result ）明显跟哪个句子无关，输出的是该包上表示出的关系，所以这里好像不能解释远程监督的作用
2、难道是生成那四个文件的时候，就是那四个预处理的子数据集？但是也不像

ps ：EntityMatcher里找实体的时候可以用ac自动机，速度会快很多
麻烦了~~
