### ISSUE TITLE
add_relation 报错

### ISSUE THREAD

**Issue by 526222883** [xiaolalala/Distant-Supervised-Chinese-Relation-Extraction#7]
未定义tail

**Comment by JazzTheSaver** [comment]
有同样问题。请问应该怎么改

**Comment by tanzf** [comment]
也遇到同样问题，请问大家改了吗？

**Comment by lzx0605** [comment]
![image](https://user-images.githubusercontent.com/67415440/203700997-1d16a2a1-a3c9-40e9-b832-9d5a8d2a8db0.png)
对于这一部分一直不能理解，为什么这里的数据是实体匹配之前的句子呢？不应该是实体匹配后的句子吗？还有为什么会一直报错呢？

**Comment by lzx0605** [comment]
@xiaofei05 作者可以解答一下吗？
